services:
  pt-accelerator:
    image: eternalcurse/pt-accelerator:latest
    container_name: pt-accelerator
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "${TZ:-Asia/Shanghai}"
      APP_PORT: "${APP_PORT:-23333}"
    volumes:
      - /etc/hosts:/etc/hosts
      - ./config:/app/config
      - ./logs:/app/logs
